# इस वर्कफ़लो फ़ाइल का नाम
name: Build Bitcoin Core for Android (ARM64)

# यह वर्कफ़लो कब चलेगा?
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# वर्कफ़लो में किए जाने वाले काम (Jobs)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # स्टेप 1: सोर्स कोड को डाउनलोड करना
      - name: Checkout Bitcoin Core source code
        uses: actions/checkout@v4

      # स्टेप 2: ज़रूरी निर्भरताओं को इंस्टॉल करना (अब Android क्रॉस-कंपाइल पैकेज के साथ)
      - name: Install build dependencies and Cross-Compilation tools
        run: |
          sudo apt-get update
          # हम Android के लिए क्रॉस-कंपाइलिंग टूलचेन और ज़रूरी लाइब्रेरी इंस्टॉल कर रहे हैं
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 curl git ca-certificates ccache cmake \
          g++-aarch64-linux-gnu binutils-aarch64-linux-gnu \
          libboost-system-dev:arm64 libboost-filesystem-dev:arm64 libboost-test-dev:arm64 libboost-thread-dev:arm64 \
          libevent-dev:arm64 libsqlite3-dev:arm64

      # स्टेप 3: बिटकॉइन कोर को कॉन्फ़िगर और कंपाइल करना (depends के बिना)
      - name: Configure and build Bitcoin Core
        env:
          # क्रॉस-कंपाइलिंग के लिए एनवायरनमेंट वेरिएबल्स सेट करना
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
          AR: aarch64-linux-gnu-ar
          RANLIB: aarch64-linux-gnu-ranlib
          STRIP: aarch64-linux-gnu-strip
        run: |
          ./autogen.sh
          # अब हम configure को बता रहे हैं कि उसे सिस्टम में इंस्टॉल की गई लाइब्रेरी का उपयोग करना है
          ./configure --host=aarch64-linux-gnu --enable-wallet --disable-tests --disable-bench --without-gui --enable-util-cli --with-boost-libdir=/usr/lib/aarch64-linux-gnu
          make -j$(nproc)

      # स्टेप 4: परिणामी फाइलों को इकट्ठा करना
      - name: Prepare artifacts for upload
        run: |
          mkdir -p release/bin
          cp src/.libs/bitcoind release/bin/
          cp src/.libs/bitcoin-cli release/bin/

      # स्टेप 5: बनी हुई फाइलों को अपलोड करना
      - name: Upload compiled binaries as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-android-arm64
          path: release/
