# इस वर्कफ़्लो फ़ाइल का नाम
name: Build Bitcoin Core for Android (ARM64)

# यह वर्कफ़्लो कब चलेगा?
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# वर्कफ़्लो में किए जाने वाले काम (Jobs)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # स्टेप 1: सोर्स कोड को डाउनलोड करना
      - name: Checkout Bitcoin Core source code
        uses: actions/checkout@v4

      # स्टेप 2: ज़रूरी निर्भरताओं को इंस्टॉल करना
      - name: Install build dependencies and Android NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 curl git ca-certificates ccache cmake
          
          # Android NDK डाउनलोड करना
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip
          
          # NDK के पाथ को सही ढंग से सेट करना
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e" >> $GITHUB_ENV
          echo "$(pwd)/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      # स्टेप 3: बिटकॉइन की निर्भरताओं को बनाना (टूलचेन फ़ाइल के साथ)
      - name: Build dependencies for Android ARM64 with Toolchain
        run: |
          cd depends
          make HOST=aarch64-linux-android -j$(nproc) CMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake CMAKE_ANDROID_API=21

      # स्टेप 4: बिटकॉइन कोर को कॉन्फ़िगर और कंपाइल करना (GUI के बिना)
      - name: Configure and build Bitcoin Core
        run: |
          ./autogen.sh
          ./configure --prefix=`pwd`/depends/aarch64-linux-android --enable-wallet --disable-tests --disable-bench --without-gui --enable-util-cli # <-- THE FIX IS HERE!
          make -j$(nproc)

      # स्टेप 5: परिणामी फाइलों को इकट्ठा करना
      - name: Prepare artifacts for upload
        run: |
          mkdir -p release/bin
          cp src/bitcoind release/bin/
          cp src/bitcoin-cli release/bin/

      # स्टेप 6: बनी हुई फाइलों को अपलोड करना
      - name: Upload compiled binaries as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-android-arm64
          path: release/
